# Generated by Django 5.1.1 on 2024-09-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_viewer',
            field=models.BooleanField(default=True),
        ),
    ]
