# Generated by Django 5.1.1 on 2024-09-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_journalist',
            field=models.BooleanField(default=True),
        ),
    ]
