# Generated by Django 5.1.1 on 2024-09-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
